#!/bin/sh

set -x
autoreconf -i -f

#if libtoolize --version > /dev/null 2>&1 ; then
#  LIBTOOLIZE="libtoolize"
#elif glibtoolize --version > /dev/null 2>&1 ; then
#  LIBTOOLIZE="glibtoolize"
#else
#  echo "Error: libtoolize can not be found in you PATH"
#  echo ""
#  exit 1
#fi

#set -x
#aclocal -I  config
#$LIBTOOLIZE -f -c
#aclocal -I config
#autoheader
#automake -a -c
#autoconf
